ir = "../rirs/treble/living_room1/living_room1_000.wav"
num_channels = 8
spectral_flatness_weight = 1
sparsity_weight = 0.5
power_envelope_weight = 0
edc_weight = 0.1
mel_edr_weight = 1
randomize_initial_params = false
random_delays = false
save_output = true
verbose = true
gradient_delta = 1e-3
gradient_delta_filter = 0.01

[Adam]
step_size = 0.4539999999999996
beta1 = 0.9
beta2 = 0.999
tolerance = 1e-5
gradient_delta = 0.03935707851130453

[SPSA]
alpha = 0.484
gamma = 0.9375
step_size = 0.605
evaluation_step_size = 0.7446
max_iterations = 1000
tolerance = 1e-5

[SimulatedAnnealing]
max_iterations = 10000000
initial_temperature = 100
init_moves = 10000
move_ctrl_sweep = 6
max_tolerance_sweep = 3
max_move_coeff = 6.0
init_move_coeff = 1.4
gain = 0.1
tolerance = 1e-5

[CNE]
population_size = 5000
max_generation = 5000
mutation_probability = 0.3
mutation_size = 0.1
select_percent = 0.9
tolerance = 1e-5

[DifferentialEvolution]
population_size = 10000
max_generation = 2000
crossover_rate = 0.6
differential_weight = 0.8
tolerance = 1e-5

[PSO]
num_particles = 100
max_iterations = 500
horizon_size = 360
tolerance = 1e-5
exploitation_factor = 2.05
exploration_factor = 2.05

[L-BFGS]
num_basis = 30
max_iterations = 1000
wolfe = 0.9
min_gradient_norm = 1e-6
factor = 1e-15
max_line_search = 50
min_step = 1e-20
max_step = 1e20

[GradientDescent]
step_size = 0.5
max_iterations = 200
tolerance = 1e-4
kappa = 0.01
phi = 0.01
momentum = 0.865
min_gain = 1e-10

[CMAES]
population_size = 0
max_iterations = 1000
tolerance = 1e-5
step_size = 0

[RandomSearch]
time_limit = 10.0