add_library(FdnOpt_options INTERFACE)
add_library(FdnOpt::FdnOpt_options ALIAS FdnOpt_options)
target_compile_features(FdnOpt_options INTERFACE cxx_std_23)

if(FDN_OPT_ENABLE_IPO)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT ipo_supported OUTPUT ipo_error)
  if(NOT ipo_supported)
    message(FATAL_ERROR "Interprocedural optimization is not supported: ${ipo_error}")
  endif()
  set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  message(STATUS "Enabling interprocedural optimization")
endif()

if(FDN_OPT_ENABLE_NATIVE_ARCH)
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options(FdnOpt_options INTERFACE -march=native)
    target_link_options(FdnOpt_options INTERFACE -march=native)
    message(STATUS "Enabling native CPU optimization")
  else()
    message(FATAL_ERROR "FDN_OPT_ENABLE_NATIVE_ARCH is only supported with Clang or GCC")
  endif()
endif()

if(FdnOpt_USE_SANITIZER)
  if(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    message(STATUS "Enabling AddressSanitizer")
    target_compile_options(FdnOpt_options INTERFACE $<$<CONFIG:Debug>:-fsanitize=address>)
    target_link_options(FdnOpt_options INTERFACE $<$<CONFIG:Debug>:-fsanitize=address>)
  endif()
endif()

include(CheckCXXSymbolExists)

if(cxx_std_20 IN_LIST CMAKE_CXX_COMPILE_FEATURES)
  set(header version)
else()
  set(header ciso646)
endif()

check_cxx_symbol_exists(_LIBCPP_VERSION ${header} LIBCPP)
if(LIBCPP)
  if(FdnOpt_ENABLE_HARDENING)
    message(STATUS "Enabling libc++ hardening")
    target_compile_definitions(
      FdnOpt_options INTERFACE $<$<CONFIG:Debug>:_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG>
                               $<$<CONFIG:RelWithDebInfo>:_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG>)
  endif()
endif()

check_cxx_symbol_exists(_STD_VERSION_HEADER_ ${header} MSVC_STL)
if(MSVC_STL)
  if(FdnOpt_ENABLE_HARDENING)
    message(STATUS "Enabling MSVC STL hardening")
    target_compile_definitions(FdnOpt_options INTERFACE $<$<CONFIG:Debug>:_MSVC_STL_HARDENING=1>
                                                        $<$<CONFIG:RelWithDebInfo>:_MSVC_STL_HARDENING=1>)
  endif()
endif()
